### ISSUE TITLE
Actual (base) prices not included in DB script

### ISSUE THREAD

**Issue by gerli** [ThatRedheadMC/Charm#5]
Not sure if this is As Designed... but you don't have any price information in here. Inventory and transaction data should probably not be here, yes, but base prices (ie Eff3 is _x_ llamas etc) seem more constant and maybe would be good to have them in the sql init script as well?

But yeah, not sure about this, happy to hear your thoughts.

**Comment by JamesGallicchio** [comment]
o.O The PRICES table has all the base prices. Or so I hope? Will check when get on home computer.

**Comment by gerli** [comment]
Well, they might be in your database but they're not in the sql file on here :)

**Comment by gerli** [comment]
Resolved with commit 0e9c4ad86f6d7ef921814b1a4b3c4971dd2bb63d
