### ISSUE TITLE
tomcat7/lib/servlet-api.jar nonexistent on tomcat installation or never added

### ISSUE THREAD

**Issue by JamesGallicchio** [ThatRedheadMC/Charm#7]
@gerli above explanation, build.sh references but the file is nonexistent. This prevents build.sh from compiling the java classes (which import classes presumably in servlet-api.jar)

**Comment by gerli** [comment]
Fixed by adding servlet-api.jar to the repository (and also copied to tomcat's lib directory, but that might have been unnecessary)
